---
title: "Ketone Tolerance in CD/KD A/J Mice"
author: "Cody Cousineau, Detrick Snyder and Dave Bridges"
date: "August 8, 2019"
output:
  html_document:
    toc: yes
    keep_md: yes
---

```{r setup, include=FALSE}
library(knitr)
#figures makde will go to directory called figures, will make them as both png and pdf files 
opts_chunk$set(fig.path='figures/',
               echo=TRUE, warning=FALSE, message=FALSE,dev=c('png','pdf'))
options(scipen = 2, digits = 3)
# set echo and message to TRUE if you want to display code blocks and code output respectively

knitr::knit_hooks$set(inline = function(x) {
  knitr:::format_sci(x, 'md')
})


superpose.eb <- function (x, y, ebl, ebu = ebl, length = 0.08, ...)
  arrows(x, y + ebu, x, y - ebl, angle = 90, code = 3,
  length = length, ...)

  
se <- function(x) sd(x, na.rm=T)/sqrt(length(x))

#load these packages, nearly always needed
library(tidyr)
library(dplyr)

# sets maize and blue color scheme
color.scheme <- c('#00274c', '#ffcb05')
```

This script was most recently run on `r date()` and can be found in `r getwd()`.

# Purpose

Analyse mRNA expression from AJ Muscles

# Experimental Details

qPCR for several ketolytic genes, done on two separate days

# Raw Data


```{r data-entry}
library(readr)
aj.mapping.file <- 'AJ Mappnig Data.csv'
run.1.file  <- 'Muscle qPCR Run 1.csv'
run.2.file <- 'Muscle qPCR Run 2.csv'

mapping.data <- read_csv(aj.mapping.file)
run.1.data <- read_csv(run.1.file) %>% mutate(Plate="First")
run.2.data <- read_csv(run.2.file) %>% mutate(Plate="Second")

run.data <- bind_rows(run.1.data,run.2.data)
```

The mapping file is in `r aj.mapping.file` and the two qPCR runs are in `r run.1.file` and `r run.2.file`

# Session Information

```{r session-info}
sessionInfo()
```

