---
title: "GDF15 Time Course ELISA"
author: "Molly C. Mulcahy"
date: "12/22/2020"
output:
  html_document:
    highlight: tango
    keep_md: yes
    number_sections: yes
    toc: yes
---

```{r setup, include=FALSE}

library(lme4)
library(readr)
library(knitr)
library(dplyr)
library(ggplot2)
library(car)

se <- function(x) sd(x, na.rm=T)/sqrt(length(x))
#figures makde will go to directory called figures, will make them as both png and pdf files 
opts_chunk$set(fig.path='figures/',
               echo=TRUE, warning=FALSE, message=FALSE,dev=c('png','pdf'))
options(scipen = 2, digits = 3)
# set echo and message to TRUE if you want to display code blocks and code output respectively

knitr::knit_hooks$set(inline = function(x) {
  knitr:::format_sci(x, 'md')
})


superpose.eb <- function (x, y, ebl, ebu = ebl, length = 0.08, ...)
  arrows(x, y + ebu, x, y - ebl, angle = 90, code = 3,
  length = length, ...)
```


# Data Entry
```{r data-entry-12-14-2020}

#Enters results from Dilution Factor = 5
my.assays.GDF15.data <- read_csv("GDF15 Time Course ELISA 1.csv",
                           col_types = cols(
                            Sample = col_character(),
                            Dilution = col_double(),
                             Well = col_factor(levels = NULL),
                            raw = col_double(),
                            Conc. = col_double()
                           ))
                   
mapping.data <-read_csv("GDF15 Time Course ELISA Mapping 1.csv",
                        col_types = cols(
                          well =	col_factor(levels = NULL),
                          ID = col_factor(levels = NULL),
                          diet	= col_factor(levels = NULL),
                          time	= col_double(),
                          study = col_factor(levels = NULL)
                        ))

full.data <- merge(mapping.data, my.assays.GDF15.data, by = "Well")%>%
  select(ID, Well, study, time, diet, study, Conc.,Raw)
non.ID<-c("blank", "pos.control")
```


# Analysis

```{r kd-time-course}
#make dataset for time course study
time.course.data<-full.data%>%
  filter(study == "time.course")%>%
  group_by(time)%>%
  summarize(average.GDF15 = mean(Conc.),
            error.GDF15 = se(Conc.),
            shapiro.GDF15 = shapiro.test(Conc.)$p.value)

time.course.data %>% filter(time=='0') %>% pull(average.GDF15) -> baseline.gdf15

#Plot of time course study- averaged
ggplot(time.course.data, aes(time, average.GDF15))+
  geom_point(col = "dodgerblue")+
  geom_errorbar(aes(ymin = average.GDF15 - error.GDF15, ymax = average.GDF15 + error.GDF15), col = "dodgerblue")+
  geom_line(col = "dodgerblue")+
  labs(title = "GDF15 in Ketogenic Diets", y= "GDF15 concentration (pg/mL)", x = "Time (days)")+
  expand_limits(x = 0, y = 0)+
  geom_hline(yintercept=baseline.gdf15, linetype = "dotdash")

ggplot(time.course.data %>% filter(!(time %in% c(1,2))),
       aes(time, average.GDF15))+
  geom_point()+
  geom_errorbar(aes(ymin = average.GDF15 - error.GDF15, 
                    ymax = average.GDF15 + error.GDF15))+
  geom_line()+
  labs(title = "", y= "GDF15 concentration (pg/mL)", x = "Time on KD (days)")+
  expand_limits(x = 0, y = 0)+
  geom_hline(yintercept=baseline.gdf15, lty = 2) +
  theme_classic() +
  theme(text=element_text(size=18))
  
# time course study-Individual plots
time.course.ID.data<-full.data%>%
  filter(study=="time.course")
ggplot(time.course.ID.data, aes(time, `Conc.`, col = ID))+
  geom_point(aes(col = ID))+
  #geom_errorbar(aes(ymin = average.GDF15 - error.GDF15, ymax = average.GDF15 + error.GDF15), col = "dodgerblue")+
  geom_line(aes(col = ID))+
  labs(title = "GDF15 in Ketogenic Diets", y= "GDF15 concentration (pg/mL)", x = "Time (days)")
```

## Statistics

```{r time-course-stats}
gdf15.stats <-
  full.data%>%
  filter(study == "time.course") %>%
  group_by(time) %>%
  summarize(T.Test=t.test(Conc., mu=baseline.gdf15)$p.value,
            Wilcox.Test = wilcox.test(Conc., mu=baseline.gdf15)$p.value)

time.course.data %>%
  full_join(gdf15.stats) %>%
  mutate(Percent.Change=average.GDF15/baseline.gdf15) %>%
  kable(caption="Summary statistics for GDF15 time course")
```
