---
title: "Maternal Data of Virign Mice during Gestation and Lactation"
author: "Noura El Habbal"
date: "2020"
output:
  html_document:
    highlight: tango
    keep_md: yes
    number_sections: yes
    toc: yes
  pdf_document:
    highlight: tango
    keep_tex: yes
    number_sections: yes
    toc: yes
---

```{r global_options, include=FALSE}
library(knitr)
#figures makde will go to directory called figures, will make them as both png and pdf files 
opts_chunk$set(fig.path='figures/',
               echo=FALSE, warning=FALSE, message=FALSE,dev=c('png','pdf'))
options(scipen = 2, digits = 3)
# set echo and message to TRUE if you want to display code blocks and code output respectively
knitr::knit_hooks$set(inline = function(x) {
  knitr:::format_sci(x, 'md')
})
superpose.eb <- function (x, y, ebl, ebu = ebl, length = 0.08, ...)
  arrows(x, y + ebu, x, y - ebl, angle = 90, code = 3,
  length = length, ...)
  
se <- function(x) sd(x, na.rm=T)/sqrt(length(x))
#load these packages, nearly always needed
library(tidyr)
library(dplyr)
library(broom)
# sets maize and blue color scheme
color.scheme <- c('#00274c', '#ffcb05')
```

# Raw Data

```{r data-files}
library(readr) #loads the readr package
Maternaldata.file <- 'Maternal MRI and Food Intake in First Parity.csv'
```

```{r data-input}
library(readr) #loads the readr package
#load sample mapping file
Maternal.data <- read_csv(Maternaldata.file, na=c("N/A",NA))  %>% mutate(MaternalGenotype = relevel(as.factor(MaternalGenotype), ref="WT")) #manually defining NA values as N/A from input file
```

Analysis

```{r body_weights_during_pregnancyandlactation}
library(ggplot2)
library(plotrix)
maternal.weights <-
  Maternal.data %>% 
  group_by(ID , MaternalGenotype) %>%
   filter(DayfromDelivery>=-22)
 
  
  ggplot(data=maternal.weights, 
      aes(y=BW,
           x=DayfromDelivery,
           col=MaternalGenotype,na.rm= T ,
           fill=MaternalGenotype, na.rm =T, ymin=15, ymax=40, xmin=-21, xmax= 21))+
       scale_x_continuous(breaks=seq(-26,16,2)) +
     #scale_y_continuous(breaks= seq(15,40,5))+ #removed this tto allow y=0 to be limit
  geom_point() +
      geom_smooth(span=0.2)  +
  expand_limits(y=0) +
  theme_classic() +
     theme(text = element_text(size=13)) +
     geom_vline(xintercept = 0, lty=2)+
  #labs(x = "Days From Delivery (0)", y= "Body Weight (g)", title="Body Weights of Dams during Gestation and Lactation") removed title from figure
    scale_fill_grey() +
    scale_color_grey() +
    theme_classic() +
    theme(text=element_text(size=18),
          axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1),
          legend.position = c(0.2,0.9)) +
    labs(y="Body Weight (g)",
         x="Days From Delivery (0)")
  
  deltaBWchangefromdelivery <-
  maternal.weights %>%
  group_by(ID,MaternalGenotype) %>%
  mutate(BW.Lact = BW - BW[DayfromDelivery==0])  %>%
  filter(DayfromDelivery>=0)
  
  ggplot(data=deltaBWchangefromdelivery,
         aes(y=BW.Lact,
             x=DayfromDelivery,
             col=MaternalGenotype, na.rm=T,
             fill=MaternalGenotype, na.rm =T, ymin=-4, ymax=8, xmin=0, xmax= 21))+
       scale_x_continuous(breaks=seq(0,21,1)) +
     scale_y_continuous(breaks= seq(-4,8,1))+
  geom_point() +
      geom_smooth ()  +
  expand_limits(x=0) +
  theme_classic() +
     theme(text = element_text(size=13)) +
  #labs(x = "Days From Delivery (0)", y= "Body Weight (g)", title="Body Weight Change from Delivery Day and during Lactation") 
    scale_fill_grey() +
    scale_color_grey() +
    theme_classic() +
    theme(text=element_text(size=18),
          axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1),
          legend.position = c(0.2,0.9)) +
    labs(y="Body Weight (g)",
         x="Days From Delivery (0)")
```
```{r postnatal-bodyweight-stats}
library(lme4)
library(lmerTest)
pnbw.lme <- lmer(BW.Lact~DayfromDelivery*MaternalGenotype + (1|ID), data=deltaBWchangefromdelivery) #If we use lm function here we would get an interaction effect of maternalgenotype:daysfromdelivery = 0.0643; to then get the effect size over the 16 days postnatal, we would do 0.0481*16 to get 0.7696grams gained more per day for KO dams. lm would not group by dam but rather would consider each data point as a unique data point, and we need to group by dam so that the function counts the true n of the dams, so we will use lmer.
pnbw.lme %>% summary() 
#But since we care about comparing the slopes of WT vs KO dam trends in weight over time (until PND16), we will use lmer function to see interaction of geonotype:time, and this function allows us to group by mouse 
fixef(pnbw.lme)['DayfromDelivery:MaternalGenotypeKO'] - fixef(pnbw.lme)['DayfromDelivery'] #this is the effect size which is the estimate of genotype:daysfromdelivery - estimate for daysfromdelivery

summary(pnbw.lme) #p=0.21, not sig change in BW posttnatal

```
```{r Fat_mass_during_pregnancyandlactation}
library(ggplot2)
library(plotrix)
maternal.weights <-
  Maternal.data %>% 
  group_by(ID , MaternalGenotype) %>%
   filter(DayfromDelivery>=-22)
  
  ggplot(data=maternal.weights, 
      aes(y=Fat,
           x=DayfromDelivery,
           col=MaternalGenotype,na.rm= T ,
           fill=MaternalGenotype, na.rm =T, ymin=0, ymax=5, xmin=-21, xmax= 21))+
       scale_x_continuous(breaks=seq(-26,16,2)) +
     #scale_y_continuous(breaks= seq(0,5,0.5))+
  geom_point() +
  geom_smooth(span=0.2)  +
  expand_limits(y=0) +
  theme_classic() +
       theme(text = element_text(size=13)) +
     geom_vline(xintercept = 0, lty=2)+
  #labs(x = "Days From Delivery (0)", y= "Fat Mass (g)", title="Fat Mass of Dams during Gestation and Lactation") 
    scale_fill_grey() +
    scale_color_grey() +
    theme_classic() +
    theme(text=element_text(size=18),
          axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1),
          legend.position = c(0.2,0.9)) +
    labs(y="Fat Mass (g)",
         x="Days From Delivery (0)")
  
  
  
  
  
    deltaFatchangefromdelivery <-
  maternal.weights %>%
  group_by(ID,MaternalGenotype) %>%
  mutate(Fat.Lact = Fat - Fat[DayfromDelivery==0])  %>%
  filter(DayfromDelivery>=0)
  
  ggplot(data=deltaFatchangefromdelivery,
         aes(y=Fat.Lact,
             x=DayfromDelivery,
             col=MaternalGenotype, na.rm=T,
             fill=MaternalGenotype, na.rm =T, ymin=-3, ymax=3, xmin=0, xmax= 21))+
       scale_x_continuous(breaks=seq(0,16,1)) +
     #scale_y_continuous(breaks= seq(-3,3,1))+
      expand_limits(y=0) +
  geom_point() +
      geom_smooth ()  +
  expand_limits(x=0) +
  theme_classic() +
       theme(text = element_text(size=13)) +
  #labs(x = "Days From Delivery (0)", y= "Fat Mass (g)", title="Fat Mass Change from Delivery Day and during Lactation")
      scale_fill_grey() +
    scale_color_grey() +
    theme_classic() +
    theme(text=element_text(size=18),
          axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1),
          legend.position = c(0.2,0.9)) +
    labs(y="Change in Fat Mass (g)",
         x="Days From Delivery (0)")
```

### Postnatal fat mass change statistics

```{r postnatal-fat-stats}
library(lme4)
library(lmerTest)
pnfat.lme <- lmer(Fat.Lact~DayfromDelivery*MaternalGenotype + (1|ID), data=deltaFatchangefromdelivery) 
fixef(pnfat.lme)['DayfromDelivery:MaternalGenotypeKO'] - fixef(pnfat.lme)['DayfromDelivery']
summary(pnfat.lme)

##This is a significant effect with p-value <0.001

predict(pnfat.lme, newdata=data.frame(DayfromDelivery=16, MaternalGenotype="KO", ID=7981)) #0.45 g more calculating day 16 change for KO, just make sure all model variables from lme are in the paranthesis 

predict(pnfat.lme, newdata=data.frame(DayfromDelivery=16, MaternalGenotype="WT", ID=7981)) #-0.63 for WT 

0.45 - (-0.63) #=1.08 effect size weight change difference between WT and KO 

1.08/ 0.63 #71% more weight than WT report this over 16 days, taking absolute value since does not make sense to divide by negative 

```

```{r lean_mass_during_pregnancyandlactation}
library(ggplot2)
library(plotrix)
maternal.weights <-
  Maternal.data %>% 
  group_by(ID , MaternalGenotype) %>%
   filter(DayfromDelivery>=-22)
  
  ggplot(data=maternal.weights, 
      aes(y=Lean,
           x=DayfromDelivery,
           col=MaternalGenotype,na.rm= T ,
           fill=MaternalGenotype, na.rm =T, ymin=10, ymax=30, xmin=-21, xmax= 21))+
       scale_x_continuous(breaks=seq(-26,16,2)) +
     #scale_y_continuous(breaks= seq(10,30,2))+
     expand_limits(y=0)+
  geom_point() +
  geom_smooth(span=0.2)  +
  expand_limits(x=0) +
  theme_classic() +
       theme(text = element_text(size=13)) +
     geom_vline(xintercept = 0, lty=2)+
  #labs(x = "Days From Delivery (0)", y= "Lean Mass (g)", title="Lean Mass of Dams during Gestation and Lactation") 
   scale_fill_grey() +
    scale_color_grey() +
    theme_classic() +
    theme(text=element_text(size=18),
          axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1),
          legend.position = c(0.2,0.9)) +
    labs(y="Lean Mass (g)",
         x="Days From Delivery (0)")
  
  
    deltaLeanchangefromdelivery <-
  maternal.weights %>%
  group_by(ID,MaternalGenotype) %>%
  mutate(Lean.Lact = Lean - Lean[DayfromDelivery==0])  %>%
  filter(DayfromDelivery>=0)
  
  ggplot(data=deltaLeanchangefromdelivery,
         aes(y=Lean.Lact,
             x=DayfromDelivery,
             col=MaternalGenotype, na.rm=T,
             fill=MaternalGenotype, na.rm =T, ymin=-3, ymax=6, xmin=0, xmax= 21))+
       scale_x_continuous(breaks=seq(0,21,1)) +
     #scale_y_continuous(breaks= seq(-3,6,1))+
    expand_limits(y=0)+
  geom_point() +
      geom_smooth ()  +
  expand_limits(x=0) +
  theme_classic() +
       theme(text = element_text(size=13)) +
  #labs(x = "Days From Delivery (0)", y= "Change in Lean Mass (g)", title="Lean Mass Change from Delivery Day and during Lactation")
   scale_fill_grey() +
    scale_color_grey() +
    theme_classic() +
    theme(text=element_text(size=18),
          axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1),
          legend.position = c(0.2,0.9)) +
    labs(y="Change in Lean Mass (g)",
         x="Days From Delivery (0)")
     
```

```{r postnatal-lean-stats}
library(lme4)
library(lmerTest)
pnlean.lme <- lmer(Lean.Lact~DayfromDelivery*MaternalGenotype + (1|ID), data=deltaLeanchangefromdelivery) 
fixef(pnlean.lme)['DayfromDelivery:MaternalGenotypeKO'] - fixef(pnlean.lme)['DayfromDelivery']
summary(pnlean.lme)

##This is not a significant effect with p-value= 0.860
```

```{r Freewater_during_pregnancyandlactation}
library(ggplot2)
library(plotrix)
maternal.weights <-
  Maternal.data %>% 
  group_by(ID , MaternalGenotype)
  
  ggplot(data=maternal.weights, 
      aes(y=FreeWater,
           x=DayfromDelivery,
           col=MaternalGenotype,na.rm= T ,
           fill=MaternalGenotype, na.rm =T, ymin=0, ymax=6, xmin=-21, xmax= 21))+
       scale_x_continuous(breaks=seq(-26,16,2)) +
     #scale_y_continuous(breaks= seq(0,6,0.5))+
    expand_limits(y=0)+
  geom_point() +
  geom_smooth()  +
  expand_limits(x=0) +
  theme_classic() +
     geom_vline(xintercept = 0, lty=2)+
  #labs(x = "Days From Delivery (0)", y= "Free Water Mass (g)", title="Free Water Mass of KO and WT Dams during Gestation and Lactation") 
   scale_fill_grey() +
    scale_color_grey() +
    theme_classic() +
    theme(text=element_text(size=18),
          axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1),
          legend.position = c(0.2,0.9)) +
    labs(y="Free Water Mass (g)",
         x="Days From Delivery (0)")
     
```
```{r Totalwater_during_pregnancyandlactation}
library(ggplot2)
library(plotrix)
maternal.weights <-
  Maternal.data %>% 

  group_by(ID , MaternalGenotype)
  
  ggplot(data=maternal.weights, 
      aes(y=TotalWater,
           x=DayfromDelivery,
           col=MaternalGenotype,na.rm= T ,
           fill=MaternalGenotype, na.rm =T, ymin=5, ymax=30, xmin=-21, xmax= 21))+
         theme_classic()  +
       scale_x_continuous(breaks=seq(-26,16,2)) +
     #scale_y_continuous(breaks= seq(5,30,5))+
     expand_limits(y=0)+
  geom_point() +
  geom_smooth()  +
  expand_limits(x=0) +
       theme_classic()  +
     geom_vline(xintercept = 0, lty=2)+
  #labs(x = "Days From Delivery (0)", y= "Total Water Mass (g)", title="Total Water Mass of KO and WT Dams during Gestation and Lactation") 
   scale_fill_grey() +
    scale_color_grey() +
    theme_classic() +
    theme(text=element_text(size=18),
          axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1),
          legend.position = c(0.2,0.9)) +
    labs(y="Total Water Mass (g)",
         x="Days From Delivery (0)")
     
```
```{r food_intake}
library(ggplot2)
maternal.weights <-
  Maternal.data %>%
  group_by(ID , MaternalGenotype)
  
  ggplot(data=maternal.weights, 
       aes(y= FoodIntake,
           x=Week,
           col=MaternalGenotype, na.rm =T)) +
    scale_x_continuous(breaks=seq(-3,1,1))+
    expand_limits(y=0)+
  geom_point() +
  geom_smooth()  +
  theme_classic() +
     geom_vline(xintercept = 0, lty=2)+
  #labs(x="Week", y="Average Food Intake (g)", title="Average Dam Weekly Food Intake before and after Delivery at around Week 4")
   scale_fill_grey() +
    scale_color_grey() +
    theme_classic() +
    theme(text=element_text(size=18),
          axis.text.x = element_text(vjust = 0.5, hjust=1),
          legend.position = c(0.2,0.9)) +
    labs(y="Average Food Intake (g)",
         x="Weeks from Delivery (0)")
  
   foodintakefromdelivery <- #data frame for food intake postpartum only
  maternal.weights %>%
  group_by(ID,MaternalGenotype) %>%
  filter(DayfromDelivery>=0)
  
  ggplot(data=foodintakefromdelivery,
         aes(y=FoodIntake,
             x=DayfromDelivery,
             col=MaternalGenotype, na.rm=T,
             fill=MaternalGenotype, na.rm =T))+
  geom_point() +
      geom_smooth ()  +
  theme_classic() +
       theme(text = element_text(size=13)) +
  #labs(x = "Days From Delivery (0)", y= "Change in Food Intake (g)", title="Food Intake from Delivery Day and during Lactation")
  scale_fill_grey() +
    scale_color_grey() +
    theme_classic() +
    theme(text=element_text(size=18),
          axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1),
          legend.position = c(0.2,0.9)) +
    labs(y="Change in Food Intake (g)",
         x="Days From Delivery (0)")

```
```{r postnatal-foodintake-stats}
library(lme4)
library(lmerTest)
pnfoodintake.lme <- lmer(FoodIntake~DayfromDelivery*MaternalGenotype + (1|ID), data=foodintakefromdelivery) 
fixef(pnfoodintake.lme)['DayfromDelivery:MaternalGenotypeKO'] - fixef(pnfoodintake.lme)['DayfromDelivery']
summary(pnfoodintake.lme)

##This is not a significant effect with p-value dayfromdelivery:genotype= 0.265

```


```{r loop_to_make_lean_fat_change}
loop_table<- function(maternal_data)
{  #maternal_data is the variable representing your table of data, this is no longer a table, but rather a set of rows and columns that you can manipulate
  
  library(dplyr);
  #the following extracts the number of rows for that table
  #you will need this to determine the size of the column you will create
  
  numrow = nrow(maternal_data);
  
  

  lean_vector <- numeric(numrow); #this is for the new columnm to store the new values yet to come
  fat_vector <- numeric(numrow);
  i=0;
  while(i<numrow)
  {
    i=i+1;
    
    #numrow is the last row number, so this loop will stop when it reaches the final row
    #i is the row index I am currently on
    
    
    #my current values
    current_ID = maternal_data[i,"ID"];
    current_lean = maternal_data[i,"Lean"];
    current_fat =  maternal_data[i,"Fat"];
    
    
    #I need some values from the next week to store them in THIS WEEK's value, so I need another loop to go to next week
    
    #i want to look forward, so I will create another loop j simulataneously
    
    future_found_value = 0;
    j=i+1;
    while(j<=numrow)
    {
      future_ID = maternal_data[j,"ID"];
      if(is.na(future_ID)==FALSE && is.na(current_ID)==FALSE)
      {
        if(future_ID == current_ID)   #we reached a future row that has the same ID as our current ID
        {
          future_lean = maternal_data[j,"Lean"];
          future_fat = maternal_data[j,"Fat"];
          lean_change = future_lean - current_lean;
          fat_change = future_fat - current_fat;
          
          lean_vector[i] = lean_change*4;
          fat_vector[i] = fat_change*9;
          
          future_found_value = 1;
          break;
        }
      }

      j=j+1;
    }
    if(future_found_value==0)
    {
      lean_vector[i] = NA;
      fat_vector[i] = NA;
      
    }
    
  }

  maternal_data$leanchange <- as.double(lean_vector);
  maternal_data$fatchange <- as.double(fat_vector);
  
  #write.csv(maternal_data, file = "MyData.csv");
  
  
  #A table with two new columns, for lean and fat change
  

  #write.csv(maternal_data, file = "MyData.csv");
  return(maternal_data);
}
```

```{r maternal_feedingefficiency}
library(ggplot2)
output <- loop_table(Maternal.data); #or use no.deliveries data to remove the dams who delivered
maternal.feedingefficiency <-
  output %>%
  group_by(ID , MaternalGenotype, Week) %>%
  mutate(caloriesconsumed=ifelse(is.na(FoodIntake)==FALSE,FoodIntake*2.91,NA))%>%
  mutate(calorieschange=ifelse(is.na(leanchange)==FALSE && is.na(leanchange)==FALSE,leanchange + fatchange,NA)) %>%
  mutate(feedingeff=ifelse(is.na(caloriesconsumed)==FALSE && is.na(calorieschange)==FALSE,(calorieschange/ caloriesconsumed)*100,NA))
write.csv(maternal.feedingefficiency, file = "MyData.csv");
  #mutate(feedingeff= 'calorieschange'/ 'caloriesconsumed', na.rm=T)

 p <- ggplot(maternal.feedingefficiency, is.na= NA,
       aes(y= feedingeff,
           x=Week,
           col=MaternalGenotype, na.rm =T, xmin=0, xmax=6.5, ymin=-200, ymax=100)) +
      scale_x_continuous(breaks=seq(0,6.5,0.5))+
    scale_y_continuous(breaks=seq(-200,100,50))+
  geom_point() +
  geom_smooth()  +
  #geom_col(aes(fill=Treatment))+
 #facet_grid(~Treatment) +
  expand_limits(x=0)+
  theme_classic() +
   theme(text = element_text(size=18))+
    geom_vline(xintercept = 3.97, lty=2)+
  #facet_grid(~Cohort)+
  #labs(x="Week", y="Feeding Efficiency",title="Feeding Efficiency of Dams per Genotype") 
scale_fill_grey() +
    scale_color_grey() +
    theme_classic() +
    theme(text=element_text(size=18),
          axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1),
          legend.position = c(0.2,0.9)) +
    labs(y="Feeding Efficiency",
         x="Week")
p

maternal.feedingefficiency %>%
  group_by(Week,MaternalGenotype) %>%
  summarize(Mean = mean(feedingeff,na.rm=T),
            Error = se(feedingeff)) %>%
  ggplot(aes(y=Mean,
         x=Week,
         ymin=Mean-Error,
         ymax=Mean+Error,
         col=MaternalGenotype)) +
  geom_point() +
  geom_errorbar() +
  geom_vline(xintercept = 3.97, lty=2)+
  # geom_vline(yintercept = 0)
scale_fill_grey() +
    scale_color_grey() +
    theme_classic() +
    theme(text=element_text(size=18),
          axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1),
          legend.position = c(0.2,0.9)) +
    labs(y="Feeding Efficiency (g)",
         x="Week")

```